# Generated by Django 3.0.3 on 2020-06-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=1000)),
                ('organizer_id', models.IntegerField()),
                ('nof_participants', models.IntegerField(max_length=6)),
                ('start_date_reg', models.DateTimeField()),
                ('end_date_reg', models.DateTimeField()),
                ('start_date_event', models.DateTimeField()),
                ('end_date_event', models.DateTimeField()),
            ],
        ),
    ]
